
name: Build

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", icon: "Windows"}
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", icon: "Linux" }
          - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", icon: "Apple" }

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake (installing hub)
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Install hub
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}


    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build sample
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

