
name: Build

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
            # - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", hub_static: "ON", hub_shared: "ON"}
            # - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", hub_static: "ON", hub_shared: "ON" }
            # - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", hub_static: "ON", hub_shared: "ON" }
            
            - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", hub_static: "ON", hub_shared: "OFF" }
            - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", hub_static: "OFF", hub_shared: "ON" }

            - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", hub_static: "ON", hub_shared: "OFF" }
            - { name: "MacOS clang", os: macos-latest, cc: "clang", cxx: "clang++", hub_static: "OFF", hub_shared: "ON" }
            #
            - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", hub_static: "ON", hub_shared: "OFF"}
            - { name: "Windows MSVC", os: windows-latest, cc: "cl.exe", cxx: "cl.exe", hub_static: "OFF", hub_shared: "ON"}

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake (installing hub)
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DBUILD_STATIC=${{ matrix.config.hub_static }} -DBUILD_SHARED=${{ matrix.config.hub_shared }}
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Install hub
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}} --parallel


    - name: Configure CMake
      run: cmake -B "${{github.workspace}}/build" -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} 
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build sample
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

